# Generated by Django 3.1.4 on 2020-12-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='test',
        ),
    ]
