# Generated by Django 3.1.4 on 2020-12-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_rating_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='test',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
