# Generated by Django 3.1.4 on 2020-12-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_name'),
        ('app', '0003_rating_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='SaveRecipe',
        ),
    ]
